sudo: false
language: python
python:
    - "3.4"
    - "3.3"
    - "2.7"
    - "2.6"
    - "pypy"

addons:
    apt:
        packages:
            - build-essential
            - python-dev
            - libxml2
            - libxml2-dev
            - libxslt-dev

# command to install dependencies
install:
    - pip install --upgrade lxml
    - pip install pytest pep8 marshmallow beautifulsoup4 ordereddict six

# command to run tests
script:
    - py.test --tb=line -vs
    - pep8 --exclude='./xbrl/gaap.py'
