sudo: false
language: python
python:
    - "3.4"
    - "3.3"
    - "2.7"
    - "2.6"
    - "pypy"

addons:
    apt:
        packages:
            - python-dev
            - build-essential
            - git-core
            - mercurial-git
            - libxml2
            - libxml2-dev
            - libxslt1-dev

# command to install dependencies
install:
    - pip install pytest pep8 marshmallow beautifulsoup4 ordereddict six
    - git clone https://github.com/amauryfa/lxml.git
    - python setup.py build --with-cython

# command to run tests
script:
    - py.test --tb=line -vs
    - pep8 --exclude='./xbrl/gaap.py'
