sudo: false
language: python
python:
    - "3.4"
    - "3.3"
    - "2.7"
    - "2.6"
    - "pypy"

addons:
    apt:
        packages:
            - python-dev
            - libxml2
            - libxml2-dev
            - libxslt1-dev
            - python3-lxml

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install git+https://github.com/amauryfa/lxml.git

# command to run tests
script:
    - py.test --tb=line -vs
    - pep8 --exclude='./xbrl/gaap.py'
