language: python
python:
    - "3.4"
    - "3.3"
    - "2.7"
    - "2.6"
    - "pypy"

# pre-pip packages
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-dev libxml2 libxml2-dev libxslt-dev

# command to install dependencies
install:
    - pip install -r requirements.txt

# command to run tests
script:
    - py.test --tb=line -vs
    - pep8 --exclude='./xbrl/gaap.py'
